from app.models.user import User
from app.models.skill import Skill
from app.models.career import Career
from app.models.user_skill import UserSkill
from app.models.career_skill import CareerSkill
from app.models.course import Course
from app.models.project import Project
from app.models.project_skill import ProjectSkill
from app.models.prediction import Prediction
from app.models.skill_gap import SkillGap
from app.models.learning_path import LearningPath
from app.models.learning_path_item import LearningPathItem